app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

app_page:
    resource: "@AppBundle/Controller/PageController.php"
    type:     annotation
    
fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'