app:
    resource: '@AppBundle/Controller/'
    type: annotation

app_product:
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

fos_user:
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'