root:
    pattern: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /%locale%/
        permanent: true
    requirements:
        _locale: "%locales%"

main_app:
    resource: "@AppBundle/Resources/config/routing/routing.yml"
    type: "be_simple_i18n"
    prefix:
        en: "/en"
        fr: "/fr"

admin_homepage:
    resource: Application\Sonata\UserBundle\Controller\DefaultController
    prefix: /

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /

sonata_user_admin_security:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /

sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /resetting

toiba_fullcalendar:
    resource: "@FullCalendarBundle/Resources/config/routing.yaml"