
api:
    host: 'api.project-symfony.fr'
    resource: "@ApiBundle/Controller/"
    type:     annotation

auth-tokens:
    host: 'api.project-symfony.fr'
    type:     rest
    resource: Application\ApiBundle\Controller\AuthTokenController

app:
    host: 'project-symfony.fr'
    resource: '@AppBundle/Controller/'
    type: annotation

app_product:
    host: 'project-symfony.fr'
    resource: "@AppBundle/Controller/ProductController.php"
    type:     annotation

fos_user:
    host: 'project-symfony.fr'
    resource: '@FOSUserBundle/Resources/config/routing/all.xml'

admin_homepage:
    host: 'sonata.project-symfony.fr'
    resource: Application\Sonata\UserBundle\Controller\DefaultController
    prefix: /

admin_area:
    host: 'sonata.project-symfony.fr'
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /sonata

_sonata_admin:
    host: 'sonata.project-symfony.fr'
    resource: .
    type: sonata_admin
    prefix: /

sonata_user_admin_security:
    host: 'sonata.project-symfony.fr'
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /

sonata_user_admin_resetting:
    host: 'sonata.project-symfony.fr'
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /resetting
