# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12

    role_hierarchy:
        ROLE_ADMIN:         ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        chain_provider:
            chain:
                providers: [auth_token_user_provider, fos_userbundle]
        fos_userbundle:
            id: fos_user.user_provider.username_email
        auth_token_user_provider:
            id: auth_token_user_provider

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api_login:
           host: ^api\.project-symfony\.fr$
           pattern: ^/login
           anonymous: true

        api_logout:
           host: ^api\.project-symfony\.fr$
           pattern: ^/logout
           stateless: true
           simple_preauth:
               authenticator: auth_token_authenticator
           provider: auth_token_user_provider
           anonymous: true

        api:
           host: ^api\.project-symfony\.fr$
           pattern: ^/(?=\s*\S).*$   #all path but not empty
           stateless: true
           simple_preauth:
               authenticator: auth_token_authenticator
           provider: auth_token_user_provider
           anonymous: true
        
        main:
            host: project-symfony.fr
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:     true
            anonymous:  true

        sonata:
            host: sonata.project-symfony.fr
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:     true
            anonymous:  true

    access_control:
        - { path: ^/login$, host: project-symfony.fr, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, host: project-symfony.fr, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, host: project-symfony.fr, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, host: project-symfony.fr, role: ROLE_ADMIN }
