services:
    auth_token_user_provider:
        class: Application\ApiBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["ApiBundle:AuthToken"]

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["ApplicationSonataUserBundle:User"]

    auth_token_authenticator:
        class:     Application\ApiBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false
